# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

default: &dockersettings
  docker:
    - image: circleci/node:13.8.0

commands:
  echomsg:
    description: just display a message
    parameters:
      mymsg:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.mymsg >>

  print_pipeline_id:
    steps:
      -run: echo $CIRCLE_WORKFLOW_ID

jobs:
  print_myname:
    <<: *dockersettings
    steps:
      - echomsg:
        mysmg: "PVE is the best"
      - echomsg:
        mymsg: $My_NAME_VAR
      - print_pipeline_id:
      
      
  save_hello_world_output:
    <<: *dockersettings
    steps:
      - run: echo "Hello world, this is PVE" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    <<: *dockersettings
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt


workflows:
  welcome:
    jobs:
      - print_myname
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
